//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

public class level : MonoBehaviour
{
	Stack<List<Transform>> arrofarrofzombie;
	public int levelNum;
	public Transform[] zombieprefabslevel;
		
	void Start ()
	{
		//set zombie rooster for each level
		arrofarrofzombie = new Stack<List<Transform>> ();
		levelNum = 1;
		fillWave ();
	}

	public List<Transform> pop(){
		if (arrofarrofzombie.Count != 0) {
						return arrofarrofzombie.Pop ();
				} else {
					//wave cleared
				}
	}

	public void fillWave(){
		//LEVEL ROOSTER EDITOR
		switch (levelNum) {
		case 1:
			//insert all wave for level 1
			CreateWave();
			CreateWave();
			break;
		}
	}

	public void CreateWave(){
		List<Transform> tempWave = new List<Transform>();
		tempWave.Add (zombieprefabslevel[0]);
		tempWave.Add (zombieprefabslevel[1]);
		tempWave.Add (zombieprefabslevel[2]);
		arrofarrofzombie.Push (tempWave);
	}
}


